#! /bin/bash -ex

#####################
# Configuration     # 							     
#####################

### Sources
UBOOT_VERSION="2016.01"
UBOOT_CONFIG="rpi_defconfig"
SRC_DIR="src"
FIRMWARE_IMG="u-boot.bin"
BOOT_SCRIPT="boot_script.txt"
BOOT_SCRIPT_IMG="boot.scr.uimg"

#####################
# Script            #
#####################

git clone -b ${UBOOT_VERSION} --depth 1 --single-branch $(git remote -v | sed -n '/.git/{p;q;}' | awk '{print $(NF-1)}') ${SRC_DIR} && . ${SRC_DIR}/build

build
